### ISSUE TITLE
Review Website Comments

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms2-website#10]
- ~~Link to Landing page should be on Full Logo including text in the upper left corner~~ (see ~~#16~~)
- ~~Tag line: Complex forms in the blink of an eye~~
- ~~Remove Read the Doc button from landing page~~
- ~~Add correct fav icon~~

- ~~Disclaimer on Landing page: Currently we support primarily~~
- ~~Getting started~~:
   - ~~How do I get an empty react app~~
   - ~~In case of  create-react-app demo app where do I put my store? (=> index.js)~~
   -  ~~DispatchRenderer should be named JSONForms~~ (moved to JSON Forms, see [here](https://github.com/eclipsesource/jsonforms/issues/839)).
   - ~~Provide import code snippet:~~
~~import Provider from 'react-redux';~~
~~import DispatchRenderer from '@jsonforms/core';~~
   - ~~Rewrite to match what needs to be done based on empty react app~~
   - ~~Comments on text in this GDOC:
https://docs.google.com/document/d/1QPlxKM4YjjttWfdbwoHeGmmy9bvY4fdzYiagepbPhec/edit?usp=sharing~~ (please see my comments within the doc)
- ~~http://jsonforms-beta.de/docs/uischema: Box in Blue with info symbol~~
- ~~Docs: Indentation of the 2nd level items in the navigation should be increased otherwise they are on indentation level as selected items in the 1st level.~~
- ~~If possible simply: http://jsonforms-beta.de/docs/uischema should also list on the detail page all subitems as links.~~ (simple, if duplicated, which I did for now)
- ~~Why does API doc open in separate window?~~
- ~~At the end: Trigger Website review by Sage (define boundaries!)~~ (see #19)

~~Add to the support page what we had on http://jsonforms.io/#/support~~ (see #15)

Examples:
~~http://jsonforms-beta.de/examples/categorization => broken~~ (see respective JSON Forms issue  [#686](https://github.com/eclipsesource/jsonforms/issues/686))
~~http://jsonforms-beta.de/examples/custom-controls => Date control broken~~ (fixed in JSON Forms)

~~Add Twitter link~~

**Comment by edgarmueller** [comment]
Please check my comments in the issue description above.
