### ISSUE TITLE
Seed code and tutorial code don't match

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms2-website#11]
In the seed, the RatingControl looks like this https://github.com/edgarmueller/jsonforms-react-seed/blob/master/src/rating.control.js, while in the tutorial it is different (see below).
![selection_062](https://user-images.githubusercontent.com/6464495/35284973-7760d142-005c-11e8-86e7-34b0570d1fc6.png)

**Comment by edgarmueller** [comment]
Fixed via e6b26d091240ce552a5510cf1948f0c83b191d21.  Also see follow-up issue #20 .
@AlexandraBuzila Can you check whether it's fine now like with #12?
