### ISSUE TITLE
Add file references for code samples

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms2-website#12]
Looking at the 'Create a renderer', 'Create a tester', 'Register the renderer' sections, there's no mention about where the listed code should go e.g. index.js, rating.control.js etc.

**Comment by edgarmueller** [comment]
Fixed via e6b26d091240ce552a5510cf1948f0c83b191d21. Mind if you check against the current state if I missed something? If so, please re-open.
