### ISSUE TITLE
Improve code styling in demo components

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms2-website#156]
The code styling in the demo boxes should look similar to other standalone code Stylings, for example the ones in the [FAQ](https://jsonforms.io/faq)

**Comment by flx-sta** [comment]
### Details
The current design with the grey rows only being als long as the line itself and then the white gaps between each row look raw and unfinished. (personal opinion)
> ![image](https://user-images.githubusercontent.com/50131232/106727255-8fe8bc80-660b-11eb-965f-1248b47bf255.png)

**Comment by sdirix** [comment]
Fixed with website redesign https://github.com/eclipsesource/jsonforms2-website/pull/165
