### ISSUE TITLE
Spacing and Links

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms2-website#18]
![jsonforms](https://user-images.githubusercontent.com/8998368/35520806-60b461f0-0518-11e8-8405-388459d288fb.png)
 * There should be a little more whitespace within the white banner to not look cramped.
 * The icons are of different height. This leads to an uncomfortable viewing experience.
 * The links in the top right corner are not visible enough for my taste. Maybe style them **bold**?

**Comment by edgarmueller** [comment]
Fixed via fac4bfa2694eed8a0d85aea27ea13944560e6c21 and de3aec3310bd87700c733f1d06272feba6c4229a.
