### ISSUE TITLE
Get rid of docusaurus2-dotenv

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms2-website#266]
This plugin breaks the local development build. We have to inject the information about the `@next` variant in a different way.

**Comment by richardj** [comment]
For development purposes i just changed it to a static value. But i suppose those version numbers need to be fetched from the main json-forms repository?

**Comment by sdirix** [comment]
Correct, at the moment the versions are determined [here](https://github.com/eclipsesource/jsonforms2-website/blob/216087e695bb9eb6995b07266ceec525da3c929a/build.sh) and then made available via `dotenv`. We need some other solution to get rid of the `dotenv` plugin.

**Comment by richardj** [comment]
For now, adding a section, that for local development you need to run `./build.sh` to populate these values would maybe work? Not a fix, but my solution eventually was to just set static values in `content/pages/index.js` to at least be able to run it locally.

**Comment by sdirix** [comment]
Hi @richardj,
Yes that would be fine with me. So in the landing page we could just render a hard coded placeholder which is then replaced via the `build.sh` script. However we must make sure that we don't have any security related malicious injections there.

**Comment by richardj** [comment]
I just tried it out, it seems that even with running the `build.sh` script, it will show an error in the browser 

```
process is not defined
ReferenceError: process is not defined
```

It seems to do with Webpack 5 not supporting Node.js Polyfills anymore, which docusaurus has a plugin for to wrap that process `docusaurus2-dotenv`. But this pluing does not work correctly anymore as well.

I suppose there are other ways to make it easier to show the versions based on the main JSON Forms repository.
