### ISSUE TITLE
Landing Page Form Breakable

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms2-website#27]
- Visit http://jsonforms.io
- Form input ```Age``` is presented with a validation error ```is a required property```
- Enter a valid value for Age in the presented form (e.g. ```89```)
- Remove the value again
- The form shows a new validation error ```should be <= 100 should be >= 18 should be integer```
- The form is now completely broken and can no longer be used. The console is full of errors.

**Comment by edgarmueller** [comment]
Thanks for pointing this out, this is fixed with RC 3. The website has been re-deployed.
