### ISSUE TITLE
How can i change language of the Dialog and Tooltips?

### ISSUE THREAD

**Issue by Bonfims** [eclipsesource/jsonforms2-website#275]
Hey, 

Is there a way to edit these labels on tooltips and dialogs, like in array buttons when they say "Add Item" and others...

Exemple:

![image](https://github.com/eclipsesource/jsonforms2-website/assets/16294667/985617fa-5e33-48e4-baa7-61bde0a7d097)

**Comment by nickgoulet** [comment]
I would love to know as well

![image](https://github.com/eclipsesource/jsonforms2-website/assets/77361895/f8d344e3-711f-4e7f-9417-1d813352c074)

**Comment by sdirix** [comment]
I missed this issue when it was opened. For anything related JSON Forms itself and not the JSON Forms website, please use the discussion forum or the JSON Forms issue tracker.

 * The [DeleteDialog is customizable](https://github.com/eclipsesource/jsonforms/commit/b4166e52ccf02fccf2538e3cf52115f27c16dfb5)
 * Regarding the `Open` of the Autocomplete: We don't override text properties of Material UI, so you can customize them via Material UI's localization support. See [here for the documentation](https://mui.com/material-ui/guides/localization/).
