### ISSUE TITLE
Has Vue2 support been dropped

### ISSUE THREAD

**Issue by richardj** [eclipsesource/jsonforms2-website#279]
The vue2 folder has disappeared from the main repository documention at tag v.3.1.1-alpha.0

Currently working on trying to improve the documentation and wondering if i could drop the references to Vue2 (and the broken links).

**Comment by sdirix** [comment]
Hi @richardj,

Yes, we will officially drop Vue 2 support with the next release, i.e. JSON Forms 3.2

For questions, please use the [discussion board](https://jsonforms.discourse.group/).
