### ISSUE TITLE
Selected Date on Landing Page is invisible

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms2-website#30]
When selecting a date in the Landing Page Form, the currently selected date in the popup is invisible.

In the attached screenshot, ```14``` is currently selected.

![image](https://user-images.githubusercontent.com/8998368/36493698-7e311ea6-1730-11e8-89a8-a159b55f0585.png)

**Comment by edgarmueller** [comment]
Fixed by pinning material-ui version, see ce392d6d9bb05fe40e451e4ce1d2a7fc41e6dd10
