### ISSUE TITLE
Review Comments

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms2-website#4]
# Landing Page
- ~~`Get Started` Button on landing page does not work~~
- ~~`Read the Docs` Button on landing page does not work~~
# Examples
- ~~Array Example missing the Wrapper to show data, schema and jsonschema~~
- ~~Rule Example missing the Wrapper to show data, schema and jsonschema~~
- ~~Categorization Example missing the Wrapper to show data, schema and jsonschema~~
- ~~Example landing missing~~
- ~~`Inferring a UI schema` Example missing~~
- ~~`Inferring both schema` Example missing~~
- ~~`Custom controls` Example missing~~
# Docs
- ~~`Landing page` : `This page lists important articles to get started below. A list of all available articles is available to the **left**.` Will there be an additional list or should this point to the list on the **right**?~~
- ~~`Getting started` -> `Usage with existing redux store` I don't get the last sentence, maybe I just miss react knowledge.~~ 
- `Layouts`
  - ~~http://jsonforms-beta.de/docs/uischema/controls does not work if opened in new tab~~
  - ~~http://jsonforms-beta.de/examples/layouts#horizontal-layout does not work if opened in new tab~~
  - ~~http://jsonforms-beta.de/examples/layouts#vertical-layout~~ does not work if opened in new tab~~
  - ~~http://jsonforms-beta.de/examples/layouts#group-layout does not work if opened in new tab, but the id is missing anyway~~
  - ~~http://jsonforms-beta.de/api/core/interfaces/group.html should be http://jsonforms-beta.de/api/core/interfaces/grouplayout.html~~
  - ~~Categorization section is different from the other three, also has an inline demo instead of a link~~
- `Rule` 
  - ~~http://jsonforms-beta.de/examples/rule does not work if opened in new tab~~
  - ~~`TODO: do we describe anywhere how to initially hide elements?` I don't really get what you want to achieve~~
  - ~~a link to http://jsonforms-beta.de/api/core/interfaces/rule.html would be good as done in the `Layouts` section~~
- `Custom Renderers`
  - ~~Core concepts about rendering the list is not inlined and stands out, looks weird~~
  - ~~contains TODOs~~
# Support
- missing
# General
- Can't click on the JSONForms Text in the title, only on the image
- ~~Copyright and imprint need spacing~~

**Comment by edgarmueller** [comment]
More suggestions:
- highlight currently selected entry in AppBar
- hightlight AppBar entries on hover

**Comment by edgarmueller** [comment]
See follow-up issues #15, #16 and #17.
