### ISSUE TITLE
Inconsistent description and behavior in rule example

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms2-website#43]
The description of the Rule example (`examples/rule`) says:

> This example uses a Rule to display an additional selection control if the 'Is Alive' checkbox is unchecked. If is is checked the control will be hidden. Give it a try!

However, in the example, the additional selection control is enabled when the 'Is Alive' checkbox is checked and is disabled (not hidden) when the checkbox is unchecked.

![selection_564](https://user-images.githubusercontent.com/6464495/49293859-99b58900-f4b1-11e8-80c6-c264ad7443d0.png)
![selection_565](https://user-images.githubusercontent.com/6464495/49293860-9b7f4c80-f4b1-11e8-9cc1-9567fd382fcf.png)

The example or the description should be updated.

**Comment by sdirix** [comment]
Fixed in the mean time
