### ISSUE TITLE
Docz Initial Review

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms2-website#61]
## Major

* [x] Cookie banner is shown often:
  1. `/docs/api` banner is shown
  2. select `Core`
  3. use back button, banner is shown again
* [x] `API` links in `/docs/available-actions` link to localhost
* [x] `/docs/available-actions` "ref resolving" link in text points to non-existing path
* [x] `/docs/tutorial`: Materal UI link is broken
* [x] `/docs/uischema/layouts`: Links to layouts are broken

## Minor

* [ ] `/docs/available-actions` multi line API specification should be styled differently
* [x] `/docs/custom-renderers`: `NOT_APPLICABL` -> `NOT_APPLICABLE`
* [x] `/docs/custom-renderers`: switch `-1` with `NOT_APPICABLE`
* [x] `/docs/custom-renderers`: enumeration has different font and is misaligned
* [x] `/docs/getting-started`: enumeration has different font and is misaligned
* [x] `/docs/renderer-sets`: Material ui link should link to its main site, not next.
* [x] `/docs/uischema/layouts`: First paragraph (in each section) is styled differently
* [x] `/docs/uischema/layouts`: There is only one demo link for one type of layout
* [x] `/docs/uischema/rules`: First paragraph is styled differently
* [x] `/docs/what-is-jsonforms`: How does it work, 2nd paragraph is styled differently
* [ ] `/examples/categorization`: Should show both categories initially, looks broken with only one
* [ ] `/examples/categorization`: Weird empty horizontal space before first category
* [ ] order of doc sections is alphabetically sorted instead of content-wise

## Nice to have

* [x] Add landing pages for docs and examples as the menus in the middle of the screen look weird
* [ ] `/docs/renderer-sets`: There should be at least some words about other renderer sets than material and vanilla.
* [x] `/docs/getting-started`: command line should be `npm ci` instead of `npm install`
* [ ] `/docs/custom-renderers`: command line should be `npm ci` instead of `npm install`
* [ ] `/docs/getting-started`: getting started and the starting section in `/docs/custom-renderers` are redundant. Suggestion: Remove the one of `/docs/custom-renderers` and link to `/docs/getting-started` or extract a common component and reuse that in both.
* [ ] `/docs/available-actions` API anchors will not survive any api change, see `/docs/available-actions#initdata-any-schema-jsonschema-uischema-uischemaelement-options-initactionoptions--ajvajv`

**Comment by edgarmueller** [comment]
Thanks for this extensive list!
